name: JavaEssentials
version: 1.1.5
main: dev.zeeppss.javaessentials.Main
author: Zeeppss
website: 'https://github.com/Zeeppss/JavaEssentials'

commands:
  clearchat:
    description: Delete the chat.
  feed:
    description: Satisfy your or other hunger.
  fly:
    description: With the command you can fly.
  gamemode:
    description: Put yourself in any X game mode.
  gm:
    description: Put yourself in any X game mode.
  heal:
    description: Heal yourself or others.
  kick:
    description: Kick a player with reason.
  ban:
    description: Banned a player with reason.
  broadcast:
    description: Cheers a text to everyone.
  bc:
    description: Cheers a text to everyone.
  afk:
    description: Afk.
  ping:
    description: Check internet fluency.
  invsee:
    description: peek at people's inventory.
  hat:
    description: Put items on the head.
  top:
    decsription: Switch locations.
  clearinventory:
    description: Cleared the inventory players.
  ci:
    decsription: Cleared the inventory players.
  invecsee:
    description: Looking at the Enderchest player.
  weather:
    description: Changing the weather in the world.
  javaessentials:
    description: Plugin info.
  js:
    description: Plugin info.
  smite:
    description: Give it a smite.
  lightning:
    description: Give it a smite.
  suicide:
    description: Kill yourself.
  help:
    description: List Commands.
  nuke:
    description: Tnt Rain Troll.
  freeze:
    description: Freeze Troll.
  banish:
    decsription: Banish Troll.
  creeper:
    description: Creeper Troll.
  nick:
    description: Nick the player with colours.
  vanish:
    description: Hiding yourself.
  v:
    description: Hiding yourself.
  rename:
    description: Rename items.
  relore:
    description: Relore items.
  workbench:
    description: Open Crafting table.
  wb:
    description: Open Crafting table.
  back:
    description: Go back to where it was before.
  message:
    description: Send messages to fellow players.
  msg:
    description: Send messages to fellow players.
  kitop:
    description: Kit Op with 1k ench levels.
  kp:
    description: Kit Op with 1k ench levels.
  repair:
    descritpion: Repair items.
  particle:
    description: Give effects particle on yourself.