name: JavaEssentials
version: 1.0.6
main: dev.zeeppss.javaessentials.Main
author: Zeeppss

commands:
  clearchat:
    description: Delete the chat.
  feed:
    description: Satisfy your or other hunger.
  fly:
    description: With the command you can fly.
  gamemode:
    description: Put yourself in any X game mode.
  gm:
    description: Put yourself in any X game mode.
  heal:
    description: Heal yourself or others.
  kick:
    description: Kick a player with reason.
  ban:
    description: Banned a player with reason.
  broadcast:
    description: Cheers a text to everyone.
  bc:
    description: Cheers a text to everyone.
  afk:
    description: Afk.
  ping:
    description: Check internet fluency.
  invsee:
    description: peek at people's inventory.
  hat:
    description: Put items on the head.
  top:
    decsription: Switch locations.
  clearinventory:
    description: Cleared the inventory players.
  ci:
    decsription: Cleared the inventory players.
