name: JavaEssentials
version: 1.0.6
main: dev.zeeppss.javaessentials.Main
author: Zeeppss

commands:
  clearchat:
    description: Lösche den Chat.
  feed:
    description: Stille dein oder anderen hunger.
  fly:
    description: Mit dem Command kannst du Fliegen.
  gamemode:
    description: Setze dich in einen X belibigen gamemode.
  gm:
    description: Setze dich in einen X belibiegen gamemode.
  heal:
    description: Heile dich oder andere.
  day:
    description: Turns the day bright.
  tp:
    description: Teleported to player.
  teleport:
    description: Teleported to player.
  broadcast:
    description: Cheers a text to everyone.
  kick:
    description: Kick a player with reason.
  ban:
    description: Banned a player with reason.
