name: JavaEssentials
version: 1.1.9
main: dev.zeeppss.javaessentials.Main
author: Zeeppss
website: 'https://github.com/Zeeppss/JavaEssentials'

commands:
  clearchat:
    description: Delete the chat.
  feed:
    description: Satisfy your or other hunger.
  fly:
    description: With the command you can fly.
  gamemode:
    description: Put yourself in any X game mode.
  gm:
    description: Put yourself in any X game mode.
  heal:
    description: Heal yourself or others.
  kick:
    description: Kick a player with reason.
  broadcast:
    description: Cheers a text to everyone.
  bc:
    description: Cheers a text to everyone.
  afk:
    description: Afk.
  ping:
    description: Check internet fluency.
  invsee:
    description: peek at people's inventory.
  hat:
    description: Put items on the head.
  top:
    decsription: Switch locations.
  clearinventory:
    description: Cleared the inventory players.
  ci:
    decsription: Cleared the inventory players.
  invecsee:
    description: Looking at the Enderchest player.
  weather:
    description: Changing the weather in the world.
  javaessentials:
    description: Plugin info.
  js:
    description: Plugin info.
  smite:
    description: Give it a smite.
  lightning:
    description: Give it a smite.
  suicide:
    description: Kill yourself.
  help:
    description: List Commands.
  nuke:
    description: Tnt Rain Troll.
  creeper:
    description: Creeper Troll.
  ip:
    description: Check ip players.
  speed:
    description: Speed integer.
  flyspeed:
    description: Set flight speed integer amount.
  workbench:
    description: Opened craftingtable.
  wb:
    description: Opened craftingtable.
  nick:
    description: Change nickname with colours prefix.
  repair:
    description: Fixed your items.
  blind:
    description: Give blindness to player.